name: GitHubActionsDemo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    jobs:
      Build:
        runs-on: ubuntu-latest
        steps:
          - run: |  
            echo "🎉 The job was triggered by event: ${{ github.event_name }}"
            uses: actions/checkout@v4

          - name: List files in the repository
          - run: |
              echo " The repository ${{ github.repositiory }} contains the following files: "
              tree

        
